'use client';
import {useEffect,useState,useRef} from 'react';
import QRCode from 'qrcode';
import {rounds} from '@/lib/game';
type Session={room:string;host?:string;player?:string};
function Deltas({values}:{values:readonly number[]}) {return <div className="deltas">{values.map((n,i)=><span key={i} className={n<0?'negative':'positive'}>{n>0?'+':''}{n} {['cash','users','trust'][i]}</span>)}</div>}
function Rules(){return <details className="rules"><summary>How to win</summary><p>Start with 100 cash, 50 users and 50 trust. Lock one decision per round. Immediate changes are shown; a hidden market event then changes the outcome for everyone. Highest cash + users + trust wins. Cash of zero or below ends your company and gives a score of zero. Trust stays between 0 and 100; users cannot fall below zero. Ties use remaining cash, then share the rank. A missed decision costs 15 cash. The presenter closes each round manually; the timer is a guide.</p></details>}
export default function Game(){
 const [session,setSession]=useState<Session|null>(null),[data,setData]=useState<any>(null),[code,setCode]=useState(''),[name,setName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[qr,setQr]=useState(''),[seconds,setSeconds]=useState(45),[running,setRunning]=useState(false),[copied,setCopied]=useState(false);
 const saving=useRef(false);
 useEffect(()=>{const q=new URLSearchParams(location.search);setCode(q.get('room')||'');try{const saved=JSON.parse(localStorage.getItem('deepseek-session')||'null');if(saved&&(!q.get('room')||saved.room===q.get('room')))setSession(saved)}catch{}},[]);
 function keep(s:Session){setSession(s);localStorage.setItem('deepseek-session',JSON.stringify(s));setData(null)}
 async function refresh(s:Session){const qs=new URLSearchParams(s as any);const r=await fetch('/api/game?'+qs,{cache:'no-store'});const d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d);}
 useEffect(()=>{if(!session)return;let active=true;let timer:ReturnType<typeof setTimeout>;async function poll(){try{await refresh(session!);if(active)setError('')}catch(e){if(active)setError((e as Error).message)}if(active)timer=setTimeout(poll,2500)}poll();return()=>{active=false;clearTimeout(timer)}},[session]);
 useEffect(()=>{if(!session?.host)return;QRCode.toDataURL(location.origin+'/?room='+session.room,{width:320,margin:2,errorCorrectionLevel:'M'}).then(setQr)},[session]);
 useEffect(()=>{setSeconds(45);setRunning(data?.phase==='choosing')},[data?.round,data?.phase]);
 useEffect(()=>{if(!running)return;const id=setInterval(()=>setSeconds(s=>{if(s<=1){setRunning(false);return 0}return s-1}),1000);return()=>clearInterval(id)},[running]);
 async function act(action:string,extra:any={}){if(saving.current)return;saving.current=true;setBusy(true);setError('');try{const r=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...session,action,...extra})});const d:any=await r.json();if(!r.ok)throw Error(d.error);if(action==='create')keep({room:d.room,host:d.host});else if(action==='join')keep({room:code.toUpperCase().trim(),player:d.player});else if(session)await refresh(session);}catch(e){setError((e as Error).message)}finally{saving.current=false;setBusy(false)}}
 const host=!!session?.host,round=data?rounds[data.round]:null,me=data?.me,phase=data?.phase;
 const activePlayers=data?.players.filter((p:any)=>!p.failed).length||0;
 const joinLink=typeof window!=='undefined'&&session?location.origin+'/?room='+session.room:'';
 function leave(){setSession(null);setData(null);localStorage.removeItem('deepseek-session')}
 return <main className={host?'presenter':''}>
 <header><a className="brand" href="/" onClick={e=>{e.preventDefault();leave()}}><span className="brandmark">D</span><span>DEEPSEEK<span className="subbrand">THE MARKET GAME</span></span></a><span className="badge">{host?'PRESENTER':session?'FOUNDER':'CLASSROOM SIMULATION'}</span></header>
 {error&&<div role="alert" className="error">{error} <button onClick={()=>session?refresh(session).catch(e=>setError(e.message)):setError('')}>Retry</button></div>}
 {!session?<div className="start"><section className="intro"><p className="eyebrow">FOUR DECISIONS. ONE COMPANY.</p><h1>Survive the<br/><span>AI market.</span></h1><p className="lead">Run your own AI company. Grow your users, earn their trust, and keep the cash flowing.</p><div className="initial"><div><strong>100</strong><span>Starting cash</span></div><div><strong>50</strong><span>Users</span></div><div><strong>50</strong><span>Trust</span></div></div></section>
 <section className="panel join"><p className="eyebrow">TAKE YOUR SEAT</p><h2>Join the game</h2><form onSubmit={e=>{e.preventDefault();act('join',{room:code.toUpperCase().trim(),name})}}><label htmlFor="room">Room code</label><input id="room" placeholder="e.g. A3F912" value={code} maxLength={6} autoCapitalize="characters" onChange={e=>setCode(e.target.value.toUpperCase())} required/><label htmlFor="company">Your company name</label><input id="company" placeholder="Choose a name for the leaderboard" value={name} maxLength={24} onChange={e=>setName(e.target.value)} required/><button className="primary" disabled={busy}>{busy?'Joining…':'Join as a founder'}</button></form><div className="separator"/><button className="secondary" disabled={busy} onClick={()=>act('create')}>Host a new game</button><p className="small">Presenters: create a room and project the QR code.</p></section></div>:!data?<div className="panel"><h2>Connecting to room {session.room}…</h2></div>:<>
 <div className="roomline"><span>ROOM <b>{session.room}</b></span><span>{data.players.length} founders</span><button className="textbutton" onClick={leave}>Leave view</button></div><div className="progress">{rounds.map((r,i)=><div key={i} className={phase!=='lobby'&&i===data.round?'current':i<data.round||phase==='finished'?'complete':''}><span>0{i+1}</span>{r.title}</div>)}</div>
 {phase==='lobby'?<div className="lobby"><section className="panel lobbyintro"><p className="eyebrow">THE MARKET OPENS SOON</p><h1>{host?'Your founders are arriving.':"You're in."}</h1><p className="lead">{host?'Ask everyone to scan the QR code and name their company. Start when the class is ready.':me?.name+' is ready to compete. Your presenter will open the first round.'}</p><div className="initial"><div><strong>100</strong><span>Cash</span></div><div><strong>50</strong><span>Users</span></div><div><strong>50</strong><span>Trust</span></div></div><Rules/><div className="names">{data.players.map((p:any)=><span key={p.id}>{p.name}</span>)}</div>{host&&<button className="primary" disabled={busy||!data.players.length} onClick={()=>act('advance',{version:data.version})}>Start round 1</button>}</section>{host&&<section className="panel qrpanel">{qr&&<img src={qr} alt="Scan to join this game" width="280" height="280"/>}<h2>{session.room}</h2><p>Scan to join on your phone</p><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(joinLink);setCopied(true)}catch{setError('Copy this join link: '+joinLink)}}}>{copied?'Join link copied':'Copy join link'}</button><p className="small break">{joinLink}</p><p className="small">Keep presenter controls on this device. The QR code shares only the player view.</p></section>}</div>:<>
 {me&&<section className="stats">{[['Cash',me.cash],['Users',me.users],['Trust',me.trust],['Company score',me.score]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</section>}
 {phase==='choosing'?<section><div className="roundheading"><div><p className="eyebrow">ROUND {data.round+1} / 4</p><h1>{round?.title}</h1><p className="lead">{round?.prompt}</p></div>{host&&<div className="timer"><strong>{seconds}s</strong><button onClick={()=>setRunning(!running)}>{running?'Pause timer':'Resume timer'}</button><span>Suggested time • close manually</span></div>}</div>
 {me?.failed?<div className="panel"><h2>Out of cash</h2><p>Your company has failed. Stay to watch the market and final leaderboard.</p></div>:<div className="options">{round?.options.map((o,i)=><button key={o.title} className={'option '+(me?.choice===i?'selected':'')} disabled={!me||me.choice!==undefined||busy} onClick={()=>act('choose',{round:data.round,option:i})}><span className="optionnum">0{i+1}</span><h2>{o.title}</h2><p>{o.desc}</p><Deltas values={o.delta}/><span className="optionaction">{me?.choice===i?'Decision locked':host?'Founder option':me?.choice!==undefined?'':'Choose this strategy'}</span></button>)}</div>}
 {me?.choice!==undefined&&<p role="status" className="notice">Decision locked. Waiting for the market event.</p>}{host&&<div className="controlbar"><p><b>{data.submitted} / {activePlayers}</b> active founders have chosen</p><button className="primary" disabled={busy} onClick={()=>{if(data.submitted<activePlayers&&!confirm('Some founders have not chosen. Reveal now? Missing decisions cost 15 cash.'))return;act('advance',{version:data.version})}}>Close choices & reveal event</button></div>}</section>:phase==='reveal'?<section className="reveal"><p className="eyebrow">MARKET EVENT • ROUND {data.round+1}</p><h1>{data.event.title}</h1><p className="lead">{data.event.desc}</p><div className="outcomes">{round?.options.map((o,i)=><div className="panel" key={o.title}><h3>{o.title}</h3><span className="small">Event impact</span><Deltas values={data.event.effects[i]}/></div>)}</div>{me&&<div className="panel personal"><h2>{me.failed?'Your company is out of cash.':'Your round result'}</h2><p>{me.history.at(-1)?.label}</p><Deltas values={me.history.at(-1)?.change||[0,0,0]}/><p className="small">Includes the original decision and market event. Trust is capped at 100.</p></div>}{host&&<div className="controlbar"><p>Explain the trade-off, then continue.</p><button className="primary" disabled={busy} onClick={()=>act('advance',{version:data.version})}>{data.round===3?'Show final results':'Open round '+(data.round+2)}</button></div>}</section>:<section className="final"><p className="eyebrow">THE MARKET HAS CLOSED</p><h1>{data.players[0]?.failed?'A tough market for everyone.':data.players[0]?.name+' leads the market.'}</h1><p className="lead">Growth matters. Trust matters. Staying solvent matters.</p><div className="panel debrief"><h2>What would customers pay for if the model were free?</h2><p>Did the winning company sell access, convenience, or something around the model? Where did openness help — and where did it make capturing value harder?</p></div>{host&&<button className="primary" disabled={busy} onClick={()=>act('create')}>Create a fresh game</button>}</section>}
 <section className="panel leaderboard"><div className="boardheading"><h2>{phase==='finished'?'Final leaderboard':'Market leaderboard'}</h2><span className="small">Score = cash + users + trust</span></div><div className="tablewrap"><table><thead><tr><th>Rank</th><th>Company</th><th>Cash</th><th>Users</th><th>Trust</th><th>Score</th></tr></thead><tbody>{data.players.map((p:any)=><tr className={me?.id===p.id?'you':''} key={p.id}><td>{1+data.players.filter((x:any)=>x.score>p.score||(x.score===p.score&&x.cash>p.cash)).length}</td><td>{p.name}{me?.id===p.id&&<span className="youtag">YOU</span>}{p.failed&&<span className="outtag">OUT OF CASH</span>}</td><td>{p.cash}</td><td>{p.users}</td><td>{p.trust}</td><td><strong>{p.score}</strong></td></tr>)}</tbody></table></div></section>
 {me&&phase==='finished'&&<details className="panel"><summary>Your decisions</summary>{me.history.map((h:any)=><div className="history" key={h.round}><b>Round {h.round+1}: {h.label}</b><Deltas values={h.change}/></div>)}</details>}<Rules/>
 </>}
 </>}
 <footer>Inspired by the DeepSeek case • Fictional companies, events and scoring • No trivia, just trade-offs.</footer>
 </main>
}

